---
fixtures:
  repositories:
    common: "git://github.com/simp/pupmod-simp-common"
    simplib: "git://github.com/simp/pupmod-simp-simplib"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
  symlinks:
    functions: "#{source_dir}"
